name: tests

on: push

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test with Maven
        run: mvn test --batch-mode --fail-at-end

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/surefire-reports/junitreports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
